name: Automated Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Tests Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Qt dependencies for testing
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0

    - name: Install project
      run: |
        pip install -e ".[test]"

    - name: Crypto tests
      run: |
        xvfb-run -a python run_tests.py test_crypto

    - name: Generator tests
      run: |
        xvfb-run -a python run_tests.py test_generator

    - name: Storage tests
      run: |
        xvfb-run -a python run_tests.py test_storage

    - name: Vault tests
      run: |
        xvfb-run -a python run_tests.py test_vault

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install security tools
      run: |
        pip install bandit safety
        pip install -e .

    - name: Bandit audit (with config)
      run: |
        bandit -r core crypto storage ui -c .bandit
      continue-on-error: true  # Don't fail on minor warnings

    - name: Vulnerability check
      run: |
        safety check --ignore 70612  # Ignore dev vulnerabilities
      continue-on-error: true
